REGRESSION(307285@main): Broke internal iOS builds https://bugs.webkit.org/show_bug.cgi?id=307591 rdar://170170052
Unreviewed build fix.

```
Source/WebKit/UIProcess/ios/WKBrowserEngineDefinitions.h:29:2: note: in module 'pal' imported from Source/WebKit/UIProcess/ios/WKBrowserEngineDefinitions.h:29:
 ^
pal/spi/cocoa/WritingToolsSPI.h:138:5: error: 'WTTextSuggestionState' has different definitions in different modules; definition in module 'pal.spi.cocoa.WritingToolsSPI' first difference is 3rd element has name 'WTTextSuggestionStateAccepted'
  ¦ WTTextSuggestionStateAccepted = 2,
WritingTools.framework/Headers/WTTextSuggestion.h:16:5: note: but in 'WritingTools.WTTextSuggestion' found 3rd element has name 'WTTextSuggestionStateRejected'
  ¦ WTTextSuggestionStateRejected = 3,
```

307285@main modified the order of the WTTextSuggestionState enum
declaration by putting them in ascending order. This should have been a
harmless change, but supposedly it could pass as a different definition
of the same type, since it does not agree exactly with what exists in
the SDK's framework header.

We fix the error by partially reverting the WritingToolsSPI.h changes
made in 307285@main.

* Source/WebCore/PAL/pal/spi/cocoa/WritingToolsSPI.h:

Canonical link: https://commits.webkit.org/307302@main